#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions
testClear

get_currentBranch
get_currentBranchType
if [[ $currentBranchType != 'master' ]]; then
	printf "\nYou must be in the master branch to init a work!\n\n"
	git status
	exit 1
fi

get_currentTagName
if [[ -z currentTagName ]]; then
	echo "$currentBranch don't have a tag name, you should give one to it"
	git status
	exit 1
fi

printf 'do you what to git init the directory like this?\n'
if [[ -e .git/hooks/pre-commit ]];then
	echo
else
	cp $installPath/gg-pre-commit .git/hooks/pre-commit
	printf "please go to the git root to cp the pre-commit\n"
	exit 1
fi

get_basedOn
if [[ $# == 1 ]]; then
	git checkout $1 > /dev/null
	if [[ $? != 0 ]];then
		echo "error go to $1, check your spell, We can go to \n"
		git branch
		git tag
		exit 1
	fi
	get_currentTagName
	if [[ -z $currentTagName ]]; then
	    echo "$1 don't have a tag name, you should give one to it"
	    git status
	    exit 1
	fi

	gggttt;echo "gg-open-branch-without-history $basedOn"
	gggttt;echo "git tag inUse-$currentTagName -a -m \"init $1 into baseOn, version $currentTagName\""
	echo "press ENTER to continue, press Ctrl+C to ESCAPE"
	read temp
	gg-open-branch-without-history $basedOn
	git add .
	git commit -a -m "init $1 into baseOn, version $currentTagName"
	git tag inUse-$currentTagName -a -m "init $1 into baseOn, tagged inUse-$currentTagName"
else
	printf "error parameter numbers!!\n"
	exit 1
fi

