#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin/gg
source $installPath/gg-functions
testClear

if [[ "$#" -lt "1" ]]; then
	printf "Please input comment\n"
	exit 1
fi

printf "Do you what to open a comment like this?\n"

gggttt;echo "git commit --allow-empty -m \"$1\""
echo "press ENTER to continue, press Ctrl+c to ESCAPE"
read temp
git commit --allow-empty -m "$1"
