#!/bin/bash
installPath=/usr/local/bin/gg
source $installPath/gg-functions
testClear

if [[ "$#" != "1" ]]; then
	printf "Please input the dev code\n"
	exit 1
fi

get_currentBranch
get_currentBranchType
if [[ $currentBranchType != 'develop' ]] && [[ $currentBranchType != 'master' ]]; then
	printf "\nYou must be in the develop or in the master branch to create a new develop branch!\n\n"
	git status
	exit 1
fi

printf "Do you what to open a new pair of branches like this?\n"
gggttt;echo "git checkout -b \"$1|develop\" \"$currentBranch\""
gggttt;echo "git checkout -b \"$1|master\" \"$currentBranch\""
echo "press ENTER to continue, press Ctrl+c to ESCAPE"
read temp
git checkout -b "$1|develop" "$currentBranch"
git checkout -b "$1|master" "$currentBranch"
