#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin/gg
source $installPath/gg-functions
testClear

errorMsg="you should input one peremeter with 'm','d' for the master and develop branch of thie devCode"

if [[ $# != 1 ]]; then
	echo "$errorMsg"
	exit 1
fi

case $1 in
"m")
	get_master
	git checkout $master;;
"d")
	get_develop
	git checkout $develop;;
*)
	echo "$errorMsg"
	exit 1
esac
