#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions
testClear

get_currentBranch
get_currentBranchType
if [ $currentBranchType != 'feature' ]; then
	printf "\nYou must be in one feature branch to update it!\n\n"
	git status
	exit 1
fi

get_develop
echo "You are in branch ||   $currentBranch   ||"
echo "Do you want to update it like this?"

gggttt;echo "git merge --no-ff $develop"
echo
echo "press ENTER to continue, press Ctrl+C to ESCAPE"
read temp

git merge --no-ff $develop -m "Merge(update) branch $develop into $currentBranch "
