#!/bin/bash

genDebugLog(){
	git --version > gg-debug.txt
	git status >> gg-debug.txt
	git branch >> gg-debug.txt
}

get_currentBranch(){
    #currentBranch=`git status | grep On\ branch | awk '{print $3 }'`
	currentBranch=`git status | grep On\ branch | sed 's#On\ branch\ \(.*\)$#\1#'|sed "s#|#\\\|#g"`
	if [ -z $currentBranch ]; then
		pointer=1
	fi
}
get_currentBranchType(){
	if [ -n "$pointer" ]; then
		currentBranchType="pointer"
		return
	fi
	get_currentBranch
	get_isTrialBranch
	if [ -z $isTrialBranch ]; then # not the trialBranch 
		temp=`echo $currentBranch | grep \/`
		if [ -n "$temp" ]; then # have a "/" struct
			currentBranchTypeAll=`echo $currentBranch|sed 's#\(.*\)\/.*#\1#'`
			temp=`echo $currentBranchTypeAll | grep master` ;[ -n "$temp" ] && currentBranchType="master" && return
			temp=`echo $currentBranchTypeAll | grep develop`;[ -n "$temp" ] && currentBranchType="develop"&& return
			temp=`echo $currentBranchTypeAll | grep feature`;[ -n "$temp" ] && currentBranchType="feature"&& return
			temp=`echo $currentBranchTypeAll | grep issues` ;[ -n "$temp" ] && currentBranchType="issues" && return
			temp=`echo $currentBranchTypeAll | grep work`   ;[ -n "$temp" ] && currentBranchType="work"   && return
		else # do not have a "/" struct
			currentBranchTypeAll=$currentBranch
			temp=`echo $currentBranchTypeAll | grep release`;[ -n "$temp" ] && currentBranchType="release"&& return
			temp=`echo $currentBranchTypeAll | grep hotfix` ;[ -n "$temp" ] && currentBranchType="hotfix" && return
			temp=`echo $currentBranchTypeAll | grep master` ;[ -n "$temp" ] && currentBranchType="master" && return
			temp=`echo $currentBranchTypeAll | grep develop`;[ -n "$temp" ] && currentBranchType="develop"&& return
			temp=`echo $currentBranchTypeAll | grep basedOn`;[ -n "$temp" ] && currentBranchType="basedOn"&& return
		fi
	else # it is a trialBranch
		currentBranchType="trial"&& return
	fi
	echo $currentBranch
	printf "can not get current BranchType name!!!!\n"
	exit 1
}

get_develop() {
	get_currentBranchType

	if [ $currentBranchType != "work" ];then
		devCode=`echo $currentBranchTypeAll|awk -F '|' '{print $1}'`
		haveDevCode=`echo $currentBranchTypeAll|grep \|`	
	else
		devCode=`echo $currentBranch|awk -F '/' '{print $2}'|awk -F '-' '{print $2}'`
		haveDevCode=`echo $currentBranch|awk -F '/' '{print $2}'|awk -F '-' '{print $3}'`
	fi

	if [ -z "$haveDevCode" ];then 
		devCode=
	fi
	if [ -n "$devCode" ]; then
		develop="$devCode|develop"
	else
		develop="develop"
	fi
}

get_master() {
	get_currentBranchType
	if [ $currentBranchType != "work" ];then
		devCode=`echo $currentBranchTypeAll|awk -F '|' '{print $1}'`
		haveDevCode=`echo $currentBranchTypeAll|grep \|`	
	else
		devCode=`echo $currentBranch|awk -F '/' '{print $2}'|awk -F '-' '{print $2}'`
		haveDevCode=`echo $currentBranch|awk -F '/' '{print $2}'|awk -F '-' '{print $3}'`
	fi

	if [ -z "$haveDevCode" ];then 
		devCode=
	fi
	if [ -n "$devCode" ]; then
		master="$devCode|master"
	else
		master="master"
	fi
}

get_feature() {
		get_develop
	if [ -z $devCode ]; then
		feature="feature"
	else
		feature="$devCode|feature"
	fi
}
get_issues() {
		get_develop
	if [ -z $devCode ]; then
		issues="issues"
	else
		issues="$devCode|issues"
	fi
}

get_version() {
	get_currentBranchType
	if [$currentBranchType != "release"] && [$currentBranchType != "hotfix"]; then
		printf "error use of this function: get_version!\n"
		exit 1
	fi
	#version=`echo $currentBranch | sed 's#.*-\(.*\)#\1#'`
	version=`echo $currentBranch|awk -F '-' '{print $2}'`
	devCode=`echo $currentBranch|awk -F '|' '{print $1}'`
	haveDevCode=`echo $currentBranch|awk -F '|' '{print $2}'`
	if [ -n "$haveDevCode" ];then
		version="$devCode-$version"
	fi
}

get_release() {
	get_develop
	if [ -z $devCode ]; then
		release="release"
	else
		release="$devCode|release"
	fi
}

get_basedOn(){
	get_master
	if [ -z $devCode ]; then
		basedOn="basedOn"
	else
		basedOn="$devCode|basedOn"
	fi  
}

get_work_basedOn(){
	work_basedOn=`echo $currentBranch|sed 's#\/\(.*\)-#\1#'`

}

get_hotfix() {
	get_master
	if [ -z $devCode ]; then
		hotfix="hotfix"
	else
		hotfix="$devCode|hotfix"
	fi
}

get_currentBranchParent(){
	#currentBranchParent=`echo $currentBranch|sed 's#\(.*\)\..*#\1#'`
	currentBranchParent=`echo $currentBranch|sed 's#\(.*\)%.*#\1#'`
}

get_isTrialBranch(){
	isTrialBranch=`echo $currentBranch|grep %`
}

get_isParentAlive(){
	git branch  > temp.txt
	cat temp.txt | grep -x \ \ $currentBranchParent > temp1.txt
	isParentAlive=`cat temp1.txt`
	rm temp.txt temp1.txt
}

get_currentSHA() {
	currentSHA=`git show|grep ^commit|awk '{print $2}'`
}

get_currentTagName() {
	get_currentSHA
	git tag -l > .gg-data-temp1.txt
	git tag -l|awk '{system("git show "$1"|grep ^commit")}'|awk '{print $2}' > .gg-data-temp2.txt
	paste .gg-data-temp1.txt .gg-data-temp2.txt > .gg-data-temp3.txt
	currentTagName=`cat .gg-data-temp3.txt|grep $currentSHA|head -n 1|awk '{print $1}'`
	rm .gg-data-temp*
}

get_currentTagVersion() {
	if [ -z $currentTagName ]; then
		get_currentTagName
	fi
	currentTagVersion=`echo $currentTagName|sed 's#inUse-\(.*\)#\1#'`
}

get_now() {
	now=`date "+%Y-%m-%d-%H-%M-%S"`
}

testClear() {
	isClear=`git status|grep Changes\ not\ staged``git status|grep Changes\ to\ be\ committed`
	if [ -n "$isClear" ]; then
		git status
		printf "\n\nwe suggest you make a commit before you do the next thing(Ctrl+C to abort the scripts)\nor you just want to go on do it?(Press enter twice for sure)"
		read temp
		read temp
	fi
}
gggttt(){
	printf "\t"
}
