#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin/gg
source $installPath/gg-functions
testClear

get_currentBranch
get_currentBranchType
if [[ $currentBranchType != 'feature' ]]; then
	printf "\nYou must be in one feature branch to update it!\n"
	git status
	exit 1
fi

get_develop
if [[ -n `echo $currentBranch | grep -- -FromBranch-` ]]; then
	father=`echo $currentBranch | awk -F '-FromBranch-' '{print $2}'`
else
	father="$develop"
fi
echo "You are in branch ||   $currentBranch   ||"
echo "Do you want to update it with the develop like this?"

gggttt;echo "git merge --no-ff \"$father\""
echo
echo "press ENTER to continue, press Ctrl+c to ESCAPE"
read temp

git merge --no-ff "$father" -m "Merge(update) branch $father into $currentBranch "
