#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin/gg
source $installPath/gg-functions
testClear

if [[ "$#" != "1" ]]; then
	printf "Please input feature name\n"
	exit 1
fi

get_currentBranch
get_currentBranchType
if [[ $currentBranchType != 'develop' ]]; then
	printf "\nYou must be in the develop branch to create a new feature branch!\n\n"
	git status
	exit 1
fi

get_develop
get_feature
printf "Do you what to open a new feature branch like this?\n"

gggttt;echo "git checkout -b $feature/$1"
echo "press ENTER to continue, press Ctrl+C to ESCAPE"
read temp
git checkout -b "$feature/$1"
