#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin/gg
source $installPath/gg-functions
testClear

get_currentBranch
get_currentBranchType
if [[ $currentBranchType != 'feature' ]]; then
	printf "\nYou must be in one feature branch!\n\n"
	git status
	exit 1
fi

get_develop
echo "You are in branch ||   $currentBranch   ||"
echo "Do you want to close it like this?"

gggttt;echo "git checkout $develop"
gggttt;echo "git merge --no-ff $currentBranch $develop"
gggttt;echo "git branch -d $currentBranch"
echo
gggttt;echo "if you meet conflicts in merges and want to abort the merge, you should delete the branch manully"
echo "press ENTER to continue, press Ctrl+C to ESCAPE"
read temp

git checkout "$develop"
git merge --no-ff "$currentBranch" "$develop" -m "Merge branch $currentBranch into $develop"\
	&& echo "press Enter to delete $currentBranch branch"\
	&& echo " press Ctrl+C not to delete it"\
	&& read temp && git branch -d $currentBranch

