#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin/gg
source $installPath/gg-functions
testClear

get_currentBranch
get_currentBranchType
if [[ "$#" != "1" ]]; then
	echo "your are in branch $currentBranch"
	printf "Please input the hotfix number\n"
	printf "Current tag names are\n"
	git tag -l
	exit 1
fi


if [[ $currentBranchType != 'master' ]]; then
	printf "\nYou must be in the master branch to create a new hotfix branch!\n\n"
	git status
	exit 1
fi

get_master
get_hotfix
printf "Do you what to open a new hotfix branch like this?\n"

gggttt;echo "git checkout -b $hotfix-$1"
echo "press ENTER to continue, press Ctrl+C to ESCAPE"
read temp
git checkout -b "$hotfix-$1"
