#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com

if [ "$#" != "1" ]; then
	printf "Please input the hotfix number~\n"
	printf "Current tag names are\n"
	git tag
	exit 1
fi

currentBranch=`git status | grep On\ branch | awk '{print $4 }'`
if [ $currentBranch != 'master' ]; then
	printf "\nYou must be in the master branch to create a new hotfix branch!\n\n"
	git status
	exit 1
fi

printf "Do you what to open a new hotfix branch like this?\n"
# 创建一个热补丁分支
printf "\tgit checkout -b hotfix-$1 master"

read temp
git checkout -b hotfix-$1 master
