#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions
testClear

if [[ "$#" != "1" ]]; then
	printf "Please input issues name~\n"
	exit 1
fi

get_currentBranch
get_currentBranchType
if [[ $currentBranchType != 'develop' ]]; then
	printf "\nYou must be in the develop branch to create a new issues branch!\n\n"
	git status
	exit 1
fi

get_develop
get_issues
printf "Do you what to open a new issues branch like this?\n"
# 创建一个特性分支
gggttt;echo "git checkout -b $issues/$1"
echo "press ENTER to continue, press Ctrl+C to ESCAPE"
read temp
git checkout -b $issues/$1
