#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin/gg
source $installPath/gg-functions
testClear

get_currentBranch
get_currentBranchType
if [[ $currentBranchType != 'issues' ]]; then
	printf "You must be in one issues branch!\n\n"
	git status
	exit 1
fi

get_develop
if [[ -n `echo $currentBranch | grep -- -FromBranch-` ]]; then
	father=`echo $currentBranch | awk -F '-FromBranch-' '{print $2}'`
else
	father="$develop"
fi
echo "You are in branch ||   $currentBranch   ||"
echo "Do you want to close it like this?"

gggttt;echo "git checkout \"$father\""
gggttt;echo "git merge --no-ff \"$currentBranch\""
gggttt;echo "git branch -d \"$currentBranch\""
echo "press ENTER to continue, press Ctrl+c to ESCAPE"
read temp

git checkout "$father"
git merge --no-ff "$currentBranch" -m "Merge issue branch $currentBranch into $father"\
	&& echo "press Enter to delete $currentBranch branch"\
	&& echo "press Ctrl+c to ESCAPE" \
	&& read temp && git branch -d "$currentBranch"
