#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin

haveFile=`ls`
if [ -z $haveFile ];then
	printf "you must have files to init\n"
	exit 1
fi

printf 'Do you what to git init the directory like this?\n'
printf '\tgit init\n'
printf '\tgit add .\n'
printf '\tgit commit -a -m "init commit"\n'
printf '\tgit checkout -b develop\n'
printf '\tcp /usr/local/bin/gg-pre-commit .git/hooks/pre-commit'
echo "press ENTER to continue, press Ctrl+C to ESCAPE"

read temp
mkdir .gg-data
touch .gg-data/gg-config
touch .gg-data/gg-info
git init
git add .
git commit -a -m "init commit"
git checkout -b develop
cp $installPath/gg-pre-commit .git/hooks/pre-commit
