#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions

get_currentBranch
get_currentBranchType
if [ $currentBranchType != 'issues' ]; then
	printf "\nYou must be in one issues branch!\n\n"
	git status
	exit 1
fi

get_develop
printf "You are in branch ||   $currentBranch   ||\n"
printf "Do you want to close it like this?\n"
# 合并完成的特性回develop
printf "\tgit checkout $develop\n"
printf "\tgit merge --no-ff $currentBranch\n"
printf "\tgit branch -D $currentBranch\n"
printf "\n if you meet conflicts in merges, you should delete the branch manully\n"
read temp

git checkout $develop
git merge --no-ff $currentBranch \
	&& printf "press Enter to delete $currentBranch branch\n" \
	&& read temp && git branch -D $currentBranch

