#!/bin/bash
installPath=/usr/local/bin/gg
source $installPath/gg-functions
testClear

if [[ "$#" != "1" ]]; then
	printf "Please input the branch name\n"
	exit 1
fi
printf "Do you want to start branch $1 without history?\n"
echo "press ENTER to continue, press Ctrl+c to ESCAPE"
read temp
	git checkout --orphan $1