#!/bin/bash
if [ "$#" != "1" ]; then
	printf "Please input version number~\n"
	printf "current tags are\n\n"
	git tag
	exit 
fi

currentBranch=`git status | grep On\ branch | awk '{print $4 }'`
if [ $currentBranch != 'develop' ]; then
	printf "\nYou must be in the develop branch to create a new release branch!\n\n"
	git status
	exit 1
fi


