#!/bin/bash
isMaster=`git rev-parse --abbrev-ref HEAD|grep master`
if [[ -n "$isMaster" ]]; then
	printf "\tYou should NOT make a commit in the master branch\n\t\tIf you have to do so, use git commit --no-verify\n"
	git --no-pager branch
	exit 1
fi