#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions

if [ "$#" != "1" ]; then
	printf "Please input release number~\n"
	printf "Current tag names are\n"
	git tag
	exit 1
fi

get_currentBranch
get_currentBranchType
if [ $currentBranchType != 'develop' ]; then
	printf "\nYou must be in the develop branch to create a new feature branch!\n\n"
	git status
	exit 1
fi

get_develop
get_release
printf "Do you what to open a new release branch like this?\n"

# 创建一个发布分支
printf "\tgit checkout -b $release-$1 $develop"

read temp
git checkout -b $release-$1 $develop
