#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin/gg
source $installPath/gg-functions
testClear

get_currentBranch
get_currentBranchType

if [[ $currentBranchType != 'develop' && $currentBranchType != 'pointer' ]]; then
	printf "\nYou must be in the develop branch or in the detached commint in the develop branch to create a new feature branch!\n\n"
	git status
	exit 1
fi

if [[ "$#" != "1" ]]; then
	echo "your are in branch $currentBranch, Please input release number"
	printf "Current tag names are\n"
	git tag
	exit 1
fi

get_release
printf "Do you what to open a new release branch like this?\n"

if [[ "$1" == "none" ]]; then
	gggttt;echo "git checkout -b \"$release\""
	echo "press ENTER to continue, press Ctrl+c to ESCAPE"
	read temp
	git checkout -b "$release"
	git commit --allow-empty -m "Start release"
else
	gggttt;echo "git checkout -b \"$release-$1\""
	echo "press ENTER to continue, press Ctrl+c to ESCAPE"
	read temp
	git checkout -b "$release-$1"
	git commit --allow-empty -m "Start release version $1"
fi

