#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin/gg
source $installPath/gg-functions
testClear

get_currentBranch
get_currentBranchType
get_version
if [[ $currentBranchType != 'release' ]]; then
	printf "\nYou must be in one release branch!\n\n"
	git status
	exit 1
fi

get_master
get_develop
echo "You are in branch ||      $currentBranch      ||"
printf "Do you want to close it like this?\n"

gggttt;echo "git checkout \"$master\""
gggttt;echo "git merge --no-ff \"$currentBranch\""
if [[ -n $version ]]; then
    gggttt;echo "git tag -a \"$version\""
fi
gggttt;echo "git checkout \"$develop\""
gggttt;echo "git merge --no-ff \"$currentBranch\""
gggttt;echo "git branch -d \"$currentBranch\""
echo;echo "if you meet conflicts in merges, you should delete the branch manully"
echo "press ENTER to continue, press Ctrl+c to ESCAPE"
read temp

git checkout "$master"
if [[ -n $version ]]; then
    git merge --no-ff "$currentBranch" -m "Merge release branch $currentBranch into $master" && git tag -a "$version" -m "$version"
else
    git merge --no-ff "$currentBranch" -m "Merge release branch into $master"
fi
git checkout "$develop"
if [[ -n $version ]]; then
git merge --no-ff "$currentBranch" -m "Merge release branch $currentBranch into $develop"\
	&& echo "press Enter to delete branch $currentBranch"\
	&& echo "press Ctrl+c to ESCAPE"\
	&& read temp &&git branch -d "$currentBranch"
else
git merge --no-ff "$currentBranch" -m "Merge release branch into $develop"\
	&& echo "press Enter to delete branch $currentBranch"\
	&& echo "press Ctrl+c to ESCAPE"\
	&& read temp &&git branch -d "$currentBranch"
fi
