#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions
testClear

get_currentBranch
get_currentBranchType
get_version
if [ $currentBranchType != 'release' ]; then
	printf "\nYou must be in one release branch!\n\n"
	git status
	exit 1
fi

get_master
get_develop
echo "You are in branch ||      $currentBranch      ||"
printf "Do you want to close it like this?\n"

gggttt;echo "git checkout $master"
gggttt;echo "git merge --no-ff $currentBranch"
gggttt;echo "git tag -a $version"
gggttt;echo "git checkout $develop"
gggttt;echo "git merge --no-ff $currentBranch"
gggttt;echo "git branch -d $currentBranch"
echo;echo "if you meet conflicts in merges, you should delete the branch manully"

read temp
git checkout $master
git merge --no-ff $currentBranch -m "Merge branch $currentBranch into $master" && git tag -a $version -m "$version"
git checkout $develop
git merge --no-ff $currentBranch -m "Merge branch $currentBranch into $develop"\
	&& echo "press Enter to delete branch $currentBranch" \
	&& read temp &&git branch -d $currentBranch

