#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions
testClear

get_currentBranch
get_currentBranchType
get_version
if [ $currentBranchType != 'release' ]; then
	printf "\nYou must be in one release branch!\n\n"
	git status
	exit 1
fi

get_master
get_develop
printf "You are in branch ||      $currentBranch      ||\n"
printf "Do you want to close it like this?\n"

printf "\tgit checkout $master\n"
printf "\tgit merge --no-ff $currentBranch\n"
printf "\tgit tag -a $version\n"
printf "\tgit checkout $develop\n"
printf "\tgit merge --no-ff $currentBranch\n"
printf "\tgit branch -d $currentBranch\n"
printf "\n if you meet conflicts in merges, you should delete the branch manully\n"

read temp
git checkout $master
git merge --no-ff $currentBranch && git tag -a $version
git checkout $develop
git merge --no-ff $currentBranch \
	&& printf "press Enter to delete branch $currentBranch" \
	&& git branch -d $currentBranch

