#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions

if [[ "$#" != "1" ]]; then
	printf "Please input the branch you are going to\n"
	git branch
	exit 1
fi
get_currentBranch
echo "$currentBranch" > .git/currentBranch.dat
git branch > temp.txt
# we think that branch name we can go to is like "  blabla"
cat temp.txt | grep -x \ \ $1  > temp1.txt
isAlive=`cat temp1.txt`
rm temp.txt temp1.txt

if [[ -z $isAlive ]]; then
	echo "can not find branch $1 that you can go to"
	echo "current branches are"
	git branch
	exit 1
fi

git stash
git checkout $1
