#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com

if [ "$#" != "1" ]; then
	printf "Please input the branch you are going to\n"
	git branch
	exit 1
fi

currentBranch=`git status | grep On\ branch | awk '{print $4 }'`
echo "$currentBranch" > .git/currentBranch.dat
git branch > temp.txt
cat temp.txt | grep -x \ \ $1  > temp1.txt
isAlive=`cat temp1.txt`
rm temp.txt temp1.txt

if [ -z $isAlive ]; then
	printf "can not find brance $1\n\n current branches are\n"
	git branch
	exit 1
fi

git stash
git checkout $1
