#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com

if [ "$#" != "1" ]; then
	printf "Please input the branch you are going to\n"
	git branch
	exit 1
fi

git tag thisIsTheStash
git stash
git checkout $1
