#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com

currentBranch=`git status | grep On\ branch | awk '{print $4 }'`
currentBranchParent=`echo $currentBranch|sed 's#\(.*\)\..*#\1#'`
isTrailBranch=`echo $currentBranch|sed 's#.*\.\(.*\)#\1#'|grep trial`

if [ $currentBranch == $currentBranchParent ] || [ -z $isTrailBranch ]; then
	printf "\nYou must be in one trial branch\n\n"
	git status
	exit 1
fi

git branch  > temp.txt
cat temp.txt | grep -x \ \ $currentBranchParent > temp1.txt
isParentAlive=`cat temp1.txt`
rm temp.txt temp1.txt
if [ -z $isParentAlive ]; then
	printf "The trials' parent branch is missing, do the job manully\n"
fi

printf "You are in branch ||      $currentBranch      ||\n"
printf "Do you want to close it like this?\n"
now=`date "+%Y-%m-%d-%H-%M-%S"`

printf "\tRecord the logs of this branch in .deletedTrailsBranchs and then\n"
printf "\tgit branch -D $currentBranch\n"
read temp 

git commit -a -m "last commit for this trials"
git checkout $currentBranchParent
echo "=================================================" >> .deletedTrailsBranchs
echo $currentBranch "deleted at" $now >> .deletedTrailsBranchs
echo
git log $currentBranchParent..$currentBranch >> .deletedTrailsBranchs


printf "press Enter to delete $currentBranch branch\n" \
	&& read temp && git branch -D $currentBranch \
	&& git add .deletedTrailsBranchs&&git commit .deletedTrailsBranchs -m "delete branch $currentBranch"


