#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions
testClear

get_currentBranch

printf "You are in branch ||      $currentBranch      ||\n"
printf "Do you want to make a trail branch like this?\n"

if [ $# == 1 ]; then
	printf "\tgit checkout -b $currentBranch/trials.$1 $currentBranch\n"
	read temp
	git checkout -b $currentBranch/trials.$1 $currentBranch
elif [ $# == 0 ]; then
	printf "\tgit checkout -b $currentBranch/trials $currentBranch\n"
	read temp
	git checkout -b $currentBranch/trials $currentBranch
else
	printf "parameters number error!"
	exit 1
fi
