#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions
testClear

get_currentBranch
get_currentBranchParent
get_isTrialBranch

if [ -z $isTrailBranch ]; then
	printf "\nYou must be in one trial branch\n\n"
	git status
	exit 1
fi

get_isParentAlive
if [ -z $isParentAlive ]; then
	printf "The trials' parent branch is missing, do the job manully\n"
fi

printf "You are in branch ||      $currentBranch      ||\n"
printf "Do you want to close it like this?\n"
now=`date "+%Y-%m-%d-%H-%M-%S"`

printf "\tRecord the logs of this branch in .gg-data/deletedTrailsBranchs and then\n"
printf "\tgit branch -D $currentBranch\n"
read temp 

git checkout $currentBranchParent
echo "=================================================" >> .gg-data/deletedTrailsBranchs
echo $currentBranch "deleted at" $now >> .gg-data/deletedTrailsBranchs
echo
git log $currentBranchParent..$currentBranch >> .gg-data/deletedTrailsBranchs


printf "press Enter to delete $currentBranch branch\n" \
	&& read temp && git branch -D $currentBranch \
	&& git add .gg-data/deletedTrailsBranchs&&git commit .gg-data/deletedTrailsBranchs -m "delete branch $currentBranch"


