#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions
testClear

get_currentBranch

echo "You are in branch ||      $currentBranch      ||"
printf "Do you want to make a trail branch like this?\n"

if [ $# == 1 ]; then
	gggttt;echo "git checkout -b $currentBranch%trials.$1"
	echo "press ENTER to continue, press Ctrl+C to ESCAPE"
	read temp
	git checkout -b $currentBranch%trials.$1
elif [ $# == 0 ]; then
	gggttt;echo "git checkout -b $currentBranch%trials"
	echo "press ENTER to continue, press Ctrl+C to ESCAPE"	
	read temp
	git checkout -b $currentBranch%trials
else
	printf "parameters number error!"
	exit 1
fi
