#!/bin/bash
installPath=/usr/local/bin/gg
source $installPath/gg-functions
testClear

get_currentBranch
get_currentBranchParent
get_isTrialBranch

if [[ -z $isTrialBranch ]]; then
	printf "\nYou must be in one trial branch\n\n"
	git status
	exit 1
fi

get_isParentAlive
if [[ -z $isParentAlive ]]; then
	printf "The trials' parent branch is missing, do the job manully\n"
	exit 1
fi

echo "You are in branch ||      $currentBranch      ||"
printf "Do you want to close it like this?\n"

gggttt;echo "git rebase \"$currentBranch\""
gggttt;echo "git checkout \"$currentBranchParent\""
gggttt;echo "git reset --hard \"$currentBranch\""
gggttt;echo "git branch -d \"$currentBranch\""
echo "if you meet conflicts in merges, you should delete the branch manully"
echo "press ENTER to continue, press Ctrl+c to ESCAPE"
read temp

git rebase "$currentBranch" && git checkout "$currentBranchParent" && git reset --hard "$currentBranch"\
	&& echo "press Enter to delete $currentBranch branch"\
	&& echo " press Ctrl+c not to delete it"\
	&& read temp && git branch -d "$currentBranch"