#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions
testClear

get_currentBranch
get_currentBranchParent
get_isTrialBranch

if [ -z $isTrailBranch ] ; then
	printf "\nYou must be in one trial branch\n\n"
	git status
	exit 1
fi

get_isParentAlive
if [ -z $isParentAlive ]; then
	printf "The trials' parent branch is missing, do the job manully\n"
fi

echo "You are in branch ||      $currentBranch      ||"
printf "Do you want to close it like this?\n"

gggttt;echo "git checkout $currentBranchParent"
gggttt;echo "git merge --no-ff $currentBranch"
gggttt;echo "git branch -D $currentBranch"
echo "if you meet conflicts in merges, you should delete the branch manully"
read temp

git checkout $currentBranchParent
git merge --no-ff $currentBranch \
	&& echo "press Enter to delete $currentBranch branch" \
	&& read temp && git branch -D $currentBranch

