#!/bin/bash
installPath=/usr/local/bin/gg
source $installPath/gg-functions
get_now
git status
printf "Do you want to tag the branch with $now?\n"
echo "press ENTER to continue, press Ctrl+c to ESCAPE"
read temp
git tag -a $now -m "time: $now"