#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions

get_currentBranch
get_currentBranchParent
get_isTrialBranch

if [ -z $isTrailBranch ] ; then
	printf "\nYou must be in one trial branch\n\n"
	git status
	exit 1
fi

git branch > temp.txt
cat temp.txt | grep -x \ \ $currentBranchParent > temp1.txt
isParentAlive=`cat temp1.txt`
rm temp.txt temp1.txt
if [ -z $isParentAlive ]; then
	printf "The trials' parent branch is missing, do the job manully\n"
fi

printf "You are in branch ||      $currentBranch      ||\n"
printf "Do you want to close it like this?\n"

printf "\tgit checkout $currentBranchParent\n"
printf "\tgit merge --no-ff $currentBranch\n"
printf "\tgit branch -D $currentBranch\n"
printf "\n if you meet conflicts in merges, you should delete the branch manully\n"
read temp

git checkout $currentBranchParent
git merge --no-ff $currentBranch \
	&& printf "press Enter to delete $currentBranch branch\n" \
	&& read temp && git branch -D $currentBranch

