#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions
testClear

get_currentBranch
get_currentBranchType
if [ $currentBranchType != 'master' ]; then
	printf "\nYou must be in the master branch to init a work!\n\n"
	git status
	exit 1
fi

get_currentTagName
if [ -z currentTagName ]; then
	printf "$currentBranch don't have a tag name, you should give one to it\n"
	git status
	exit 1
fi

printf 'do you what to git init the directory like this?\n'
cp /usr/local/bin/gg-pre-commit .git/hooks/pre-commit\
	|| printf "please go to the git root to cp the pre-commit\n"\
	&& exit 1

get_basedOn
if [ $# == 0 ];then
	printf "\tgit checkout -b $basedOn\n"
	read temp
	git checkout -b $basedOn
	git tag inUse-$currentTagName -a -m "init $master into baseOn, version $currentTagName$"
elif [ $# == 1 ]
	printf "\tgit checkout $1\n"
	printf "\tgit checkout -b $basedOn\n"
	
	read temp
	git checkout $1 \
		|| printf "error go to $#\n check your spell\n We can go to \n" \
		&& git branch \
		&& git tag \
		&& exit 1
	get_currentTagName
	if [ -z $currentTagName ]; then
	    printf "$1 don't have a tag name, you should give one to it\n"
	    git status
	    exit 1
	fi

	git checkout -b $basedOn
	git tag inUse-$currentTagName -a -m "init $master into baseOn, version $currentTagName$"
else
	printf "error parameter numbers!!\n"
	exit 1
fi

read temp


