#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com



printf 'do you what to git init the directory like this?\n'
printf '\tgit init\n'
printf '\tgit add .\n'
printf '\tgit commit -a -m "init commit"\n'
printf '\tgit checkout -b develop master\n'
printf '\tcp /usr/local/bin/gg-pre-commit .git/hooks/pre-commit'

read temp
git init
git add .
git commit -a -m "init commit"
git checkout -b  develop master
cp /usr/local/bin/gg-pre-commit .git/hooks/pre-commit

