#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions
get_currentBranch
get_currentBranchType
if [ $currentBranchType != 'master' ]; then
	printf "\nYou must be in the master branch to init a work!\n\n"
	git status
	exit 1
fi

printf 'do you what to git init the directory like this?\n'
printf '\tcp /usr/local/bin/gg-pre-commit .git/hooks/pre-commit'
cp /usr/local/bin/gg-pre-commit .git/hooks/pre-commit

get_basedOn
if [ $# == 0 ];then
	printf "\tgit checkout -b $basedOn\n"
	read temp
	git checkout -b $basedOn
elif [ $# == 1 ]
	printf "\t git checkout $1\n"
	printf "\tgit checkout -b $basedOn\n"
	
	read temp
	git checkout $1 \
		|| printf "error go to $#\n check your spell\n We can go to \n" \
		&& git branch \
		&& git tag \
		&& exit 1
	git checkout -b $basedOn
else
	printf "error parameter numbers!!\n"
	exit 1
fi

read temp


