#!/bin/bash
#
#         (__)                     gg
#         (oo)
#   /------\/               Distributed under
#  / |    ||             the GNU GPL v3 License
# *  /\---/\
#    ~~   ~~               http://www.gnu.org
#
#
# 2014-08-02
#
# Author: wujinnnnn@gmail.com
installPath=/usr/local/bin
source $installPath/gg-functions
testClear

get_currentBranch
thisWorkBranch=$currentBranch
get_currentBranchType
thisWorkBranchTypeAll=$currentBranchTypeAll
if [[ $currentBranchType != 'work' ]]; then
	printf "\nYou must be in the work branch to make a update!\n\n"
	git status
	exit 1
fi

get_basedOn
echo $work_basedOn

if [[ $# == 1 ]]; then
	git checkout $1 > /dev/null
	if [[ $? != 0 ]];then
		printf "error go to $#\n check your spell\n We can go to \n"
		git branch
		git tag
		exit 1
	fi
	get_currentTagName
	get_currentTagVersion
	printf "Do you want to update your work branch like this?\n"
	gggttt;echo "git checkout -b $thisWorkBranchTypeAll/basedOn-$currentTagVersion"
	gggttt;echo "git merge --no-ff $currentTagName -m \"update $thisWorkBranch with $currentTagName\""
	echo "press ENTER to continue, press Ctrl+C to ESCAPE"

	read temp
	git checkout -b $thisWorkBranchTypeAll/basedOn-$currentTagVersion
	git merge --no-ff $currentTagName -m "update $thisWorkBranch with $currentTagName"

else
	printf "please input the tag name you want to update with\n"
	git tag | grep inUse
	exit 1
fi
