#!/bin/bash
read -p "where do you want to install the scripts(without the last '/')[/usr/local/bin is the default if you press Enter]:" inputStr
installPath=/usr/local/bin
if [[ -n "$inputStr" ]]; then
	installPath=$inputStr
fi

rm *~
sed "s#installPath=.*#installPath=$installPath#g" -i gg-*
sudo rm $installPath/gg-*
sudo cp gg-* $installPath

printf "install done!\nyou should read the README.md carefully is case of big changes in the usage of the scripts\n"
